### ISSUE TITLE
Add Privacy Manifest File

### ISSUE THREAD

**Issue by rudrankriyam** [lzell/AIProxySwift#28]
Apple has introduced privacy manifest files for generating the privacy labels in App Store Connect. A privacy manifest file makes adding privacy information easier as AIProxy collects each request's Device ID and IP Address.

More information about the update here: https://developer.apple.com/support/third-party-SDK-requirements/

And technical information on privacy manifests here: https://developer.apple.com/documentation/bundleresources/privacy_manifest_files/describing_data_use_in_privacy_manifests

**Comment by lzell** [comment]
Add `NSPrivacyCollectedDataTypeDeviceID`

![Screenshot 2024-10-17 at 15 31 01](https://github.com/user-attachments/assets/2106a11c-f62e-4a32-88c4-4e3d635db738)

**Comment by lzell** [comment]
@rudrankriyam thanks for filing this! I have the privacy manifest working with the following format: 
![Screenshot 2024-10-17 at 19 49 41](https://github.com/user-attachments/assets/f27fe3ea-eeb1-41eb-a0a2-dfe264e27692)

If you generate the privacy report from an Archived build:
![Screenshot 2024-10-17 at 19 52 54](https://github.com/user-attachments/assets/d7d74f3b-3b0c-44f4-b620-b37ebdce174a)

You will see a report like this:
![Screenshot 2024-10-17 at 19 54 04](https://github.com/user-attachments/assets/bde91a9c-87f4-4897-8428-b391f150e8e8)
